### ISSUE TITLE
petscx vs petsc without julia

### ISSUE THREAD

**Issue by fab6** [jkozdon/PETScX.jl#6]
Hi,
I am quite new to julia and have even less experience with petsc, though I am trying to get into both a bit more for CFD modeling.
May I ask what low level interface face means? For my understanding this would mean that the heavy vector/matrix/mpi-handling and solving would be done by petsc itself and the interface and setup is done with julia.
So performance wise it would be very similar, I assume.
Best
Fab

**Comment by jkozdon** [comment]
@fab6: not sure yet. I am trying to rebuild [PETSc.jl](https://github.com/JuliaParallel/PETSc.jl) to allow some more flexibility and fix some of the deficiencies (such as lack of testing, MPI support, CUDA support, multiple PETSc libraries, etc.)

> For my understanding this would mean that the heavy vector/matrix/mpi-handling and solving would be done by petsc itself and the interface and setup is done with julia.

I think that's about right. My aim is be able to use PETSc for model setup and lean on PETSc for the solvers.

**Comment by fab6** [comment]
ok, I think I get it... 
thank you for the quick response!
